### ISSUE TITLE
Retrieving topic fails

### ISSUE THREAD

**Issue by mmittapalli** [pozil/pub-sub-api-java-client#2]
I am getting the below error, the same credentials and topic/channel works fine with EMPConnector (CometD), I have added Case object into CDC events

Aug 03, 2022 4:30:09 PM org.salesforce.demo.PubSubApiClient retrieveTopic
INFO: PubSub API: retrieving topic /data/CaseChangeEvent...
Aug 03, 2022 4:31:13 PM org.salesforce.demo.PubSubApiClient main
SEVERE: Failed to retrieve topic /data/CaseChangeEvent: UNAVAILABLE: io exception
org.salesforce.demo.PubSubApiClient$PubSubException: Failed to retrieve topic /data/CaseChangeEvent: UNAVAILABLE: io exception

**Comment by mmittapalli** [comment]
I can clearly see channel gets opened for "api.pubsub.salesforce.com:7443" but somehow not able to retrieve topic with above name

**Comment by pozil** [comment]
Hi @mmittapalli, I haven't seen this error before.

Usually you get this error when the CDC event is not activated in setup:
```
SEVERE: Failed to retrieve topic /data/AccountChangeEvent: NOT_FOUND: The topic information for org CORE/prod/00D58000000arpqEAA and topic /data/AccountChangeEvent not found. Ensure the topic name is correct and that the topic exists. rpcId: 547bb650-7f51-4b3e-bb1f-f65fe154d47a
```

I was able to test a `CaseChangeEvent` with no issues so I wonder what's the problem.
What kind of Org are you using and are there any specific access rights that you have configured on Cases?

**Comment by mmittapalli** [comment]
I am working on developer sandbox, and I activated the Case object in CDC setup
And full error message if that helps

```
INFO: PubSub API: connecting to api.pubsub.salesforce.com:7443...
Aug 04, 2022 11:01:28 AM org.salesforce.demo.PubSubApiClient connect
INFO: connection successful
Aug 04, 2022 11:01:28 AM org.salesforce.demo.PubSubApiClient retrieveTopic
INFO: PubSub API: retrieving topic /data/CaseChangeEvent...
Aug 04, 2022 11:02:32 AM org.salesforce.demo.PubSubApiClient main
SEVERE: Failed to retrieve topic /data/CaseChangeEvent: UNAVAILABLE: io exception
org.salesforce.demo.PubSubApiClient$PubSubException: Failed to retrieve topic /data/CaseChangeEvent: UNAVAILABLE: io exception
	at org.salesforce.demo.PubSubApiClient.retrieveTopic(PubSubApiClient.java:84)
	at org.salesforce.demo.PubSubApiClient.retrieveTopicSchema(PubSubApiClient.java:89)
	at org.salesforce.demo.PubSubApiClient.main(PubSubApiClient.java:128)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
	at com.salesforce.eventbus.protobuf.PubSubGrpc$PubSubBlockingStub.getTopic(PubSubGrpc.java:538)
	at org.salesforce.demo.PubSubApiClient.retrieveTopic(PubSubApiClient.java:82)
	... 2 more
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: api.pubsub.salesforce.com/54.244.32.61:7443
Caused by: java.net.ConnectException: Connection timed out: no further information
	at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
```

**Comment by mmittapalli** [comment]
Organization Edition=Unlimited Edition

**Comment by pozil** [comment]
Thanks for the additional details @mmittapalli .

This bit doesn't look good at all:
```
Connection timed out: no further information: api.pubsub.salesforce.com/54.244.32.61:7443
```

I don't understand why there's an IP address after the domain name.
Can you double check your settings in `config.properties`?
Also, do you have a proxy or other specific network configuration such as a VPN that could affect this?

**Comment by mmittapalli** [comment]
Thanks @pozil 
It worked after getting off from corporate VPN, Thank you so much for prompt responses.
