### ISSUE TITLE
Retrieve Topic Fails

### ISSUE THREAD

**Issue by PKansaraBain** [pozil/pub-sub-api-java-client#4]
I am getting issue while retrieve the PlatformEvent. Is this only work with CDC only ?
Please look into below Error and suggest .
```
Sep 07, 2022 1:07:05 PM org.salesforce.demo.PubSubApiClient connect
INFO: PubSub API: connecting to api.pubsub.salesforce.com:7443...
Sep 07, 2022 1:07:06 PM org.salesforce.demo.PubSubApiClient retrieveTopic
INFO: PubSub API: retrieving topic Data/gRPC_Test_Event...
Sep 07, 2022 1:08:09 PM org.salesforce.demo.PubSubApiClient main
SEVERE: Failed to retrieve topic Data/gRPC_Test_Event: UNAVAILABLE: io exception
org.salesforce.demo.PubSubApiClient$PubSubException: Failed to retrieve topic Data/gRPC_Test_Event: UNAVAILABLE: io exception
        at org.salesforce.demo.PubSubApiClient.retrieveTopic(PubSubApiClient.java:83)
        at org.salesforce.demo.PubSubApiClient.retrieveTopicSchema(PubSubApiClient.java:88)
        at org.salesforce.demo.PubSubApiClient.main(PubSubApiClient.java:127)
```

**Comment by pozil** [comment]
Hi @PKansaraBain this is happening because `Data/gRPC_Test_Event` not a valid event channel.
What's the API name of the event?

**Comment by PKansaraBain** [comment]
The API name of the platform event is "gRPC_Test_Event__e", I have tried with "/gRPC_Test_Event__e", "sobjects/gRPC_Test_Event__e" & "gRPC_Test_Event__e" as well.

**Comment by pozil** [comment]
The Pub Sub API is compatible with platform events.
For a custom PE, this is the kind of format that is expected for the channel: `/event/gRPC_Test_Event__e `.
Note that the `data` prefix (lowercase) is for CDC events.

**Comment by PKansaraBain** [comment]
with event prefix also I am getting same error. Not sure If I need to make changes in other file in code !

SEVERE: Failed to retrieve topic /event/gRPC_Test_Event__e: UNAVAILABLE: io exception
org.salesforce.demo.PubSubApiClient$PubSubException: Failed to retrieve topic /event/gRPC_Test_Event__e: UNAVAILABLE: io exception

**Comment by pozil** [comment]
I just ran a test and I can confirm that it works on my end.
Can you double check you org configuration?
Is the platform event deployed and can you receive it with a tool like the [Streaming Monitor](https://appexchange.salesforce.com/appxListingDetail?listingId=a0N3A00000FYEEWUA5)?


```
Sep 07, 2022 1:19:23 PM org.salesforce.demo.PubSubApiClient connect
INFO: PubSub API: retrieving Salesforce session...
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Sep 07, 2022 1:19:24 PM org.salesforce.demo.auth.AuthenticationHelper login
INFO: Logged as trail@pozil.com on https://pozil-dev-ed.my.salesforce.com
Sep 07, 2022 1:19:24 PM org.salesforce.demo.PubSubApiClient connect
INFO: PubSub API: connecting to api.pubsub.salesforce.com:7443...
Sep 07, 2022 1:19:42 PM org.salesforce.demo.PubSubApiClient retrieveTopic
INFO: PubSub API: retrieving topic /event/Sample__e...
Sep 07, 2022 1:19:45 PM org.salesforce.demo.PubSubApiClient retrieveTopicSchema
INFO: PubSub API: retrieving schema for topic /event/Sample__e...
Sep 07, 2022 1:19:46 PM org.salesforce.demo.PubSubApiClient subscribe
INFO: PubSub API: subscribing to /event/Sample__e and waiting for 1 events...
```

**Comment by PKansaraBain** [comment]
This one seems strange. I confirmed it with Streaming Monitor and it's working as expected. I mean I can see event there. 
```

pubSub.endpoint=api.pubsub.salesforce.com:7443
pubSub.topicName=/event/gRPC_Test_Event__e
pubSub.eventReceiveLimit=1

```
Above is how  I am passing to config in java code.

I have also tried with restarting IDE.

Not sure what to do here.
Attaching Screenshot of my Event:
![image](https://user-images.githubusercontent.com/87303778/188878324-112e58c8-6733-42d0-b674-7b3e8ba8a55d.png)

**Comment by pozil** [comment]
Weird. Your config looks good to me and I'm running short on ideas.
Could it be a problem with your org credentials (hitting the wrong org)?

How about you test the `/data/AccountChangeEvent` CDC event?
Remember to activate in your org beforehand.

**Comment by PKansaraBain** [comment]
I have double check the Org credentials. It's correct one only. I am also able to get response from postman for the same Event.

/data/AccountChangeEvent is also giving the same issue.
This one is really Weird.

I am checking with new Event. I will keep you posted if I found any thing. Thanks for the help.

**Comment by mmittapalli** [comment]
Are you using VPN? I have issues subscribing to channel with VPN on but works without.

**Comment by PKansaraBain** [comment]
Nope. I am not using VPN here, Connection with Org is fine only issue with getting Events. 
Also, I tried with my local Org. It did partially work there. I was able to get the Payload but Events are stills not coming. It gives different error there.

**Comment by meruzhan79** [comment]
Hello, I also got the same error. After I added the ssl debug I noticed that there could be an issue with the TLS protocol. By default I used the jdk 1.8 (this version supports up to TLS 1.2). However, I noticed that jdk 11 b27 (this version supports TLS 1.3) would be Ok (I did not test it yet). I was wondering to know which jdk version did you use on your side?

javax.net.ssl|DEBUG|01|main|2022-09-14 12:41:50.836 CDT|SSLSocketImpl.java:496|duplex close of SSLSocket
javax.net.ssl|DEBUG|01|main|2022-09-14 12:41:50.837 CDT|SSLSocketImpl.java:1601|close the underlying socket
javax.net.ssl|DEBUG|01|main|2022-09-14 12:41:50.838 CDT|SSLSocketImpl.java:1620|close the SSL connection (initiative)
javax.net.ssl|DEBUG|01|main|2022-09-14 12:41:50.839 CDT|SSLSocketImpl.java:753|close inbound of SSLSocket
javax.net.ssl|WARNING|01|main|2022-09-14 12:41:50.840 CDT|SSLSocketImpl.java:514|SSLSocket duplex close failed (
"throwable" : {
  java.net.SocketException: Socket is closed
        at java.base/java.net.Socket.shutdownInput(Socket.java:1538)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.shutdownInput(BaseSSLSocketImpl.java:218)

**Comment by pozil** [comment]
@meruzhan79 thanks for bringing this to light.
I've used JDK 11 as you can see in the POM config here:
https://github.com/pozil/pub-sub-api-java-client/blob/main/pom.xml#L12

You should get an error if you try to build with an older JDK.
